-- =============================================================================
-- 03_warehouse_tables.sql  —  Gold / Warehouse Layer (Star Schema)
-- Conformed dimensions + fact tables.
--
-- SCD Type 2:  dim_customer, dim_supplier
-- SCD Type 1:  dim_product (overwrite on change)
-- Static dims: dim_date, dim_geography, dim_shipping_mode
--
-- Partitioning note:
--   MySQL does not allow FK constraints on partitioned tables. FK relationships
--   on fact tables are therefore enforced at the ETL layer (not via DDL).
--   The intended FK relationships are documented as comments for clarity.
-- =============================================================================

use warehouse;

-- ---------------------------------------------------------------------------
-- warehouse.dim_date
-- Pre-generated calendar dimension (generated by src/transformations/date_dim.py).
-- date_key format: YYYYMMDD (integer) — compact, fast to join.
-- ---------------------------------------------------------------------------
create table if not exists warehouse.dim_date (
    date_key        int             not null,
    full_date       date            not null,
    day_of_week     tinyint,        -- 1 = Sunday … 7 = Saturday
    day_name        varchar(10),
    day_of_month    tinyint,
    day_of_year     smallint,
    week_of_year    tinyint,
    month_num       tinyint,
    month_name      varchar(10),
    quarter_num     tinyint,
    year_num        smallint,
    fiscal_quarter  tinyint,        -- assumes fiscal year = calendar year; adjust if needed
    fiscal_year     smallint,
    is_weekend      tinyint(1),
    is_holiday      tinyint(1)      default 0,

    primary key (date_key),
    index idx_full_date    (full_date),
    index idx_year_month   (year_num, month_num)
) engine = InnoDB
  default charset = utf8mb4
  collate = utf8mb4_unicode_ci;


-- ---------------------------------------------------------------------------
-- warehouse.dim_shipping_mode
-- Small reference dimension; loaded once from source distinct values.
-- ---------------------------------------------------------------------------
create table if not exists warehouse.dim_shipping_mode (
    shipping_mode_key   tinyint         auto_increment primary key,
    shipping_mode_name  varchar(50)     not null,
    avg_days_committed  tinyint,        -- SLA days per mode (Standard=5, First=1, etc.)
    service_tier        varchar(20),    -- 'economy' | 'standard' | 'express' | 'same-day'

    unique key uq_shipping_mode_name (shipping_mode_name)
) engine = InnoDB
  default charset = utf8mb4
  collate = utf8mb4_unicode_ci;


-- ---------------------------------------------------------------------------
-- warehouse.dim_geography
-- Region / country / state / city hierarchy derived from order address fields.
-- Natural key: (order_country, order_state, order_city) — unique together.
-- ---------------------------------------------------------------------------
create table if not exists warehouse.dim_geography (
    geography_key   int             auto_increment primary key,
    market          varchar(50),
    order_region    varchar(100),
    order_country   varchar(100),
    order_state     varchar(100),
    order_city      varchar(100),
    latitude        decimal(10,6),
    longitude       decimal(10,6),

    unique key uq_geography (order_country, order_state, order_city),
    index idx_market        (market),
    index idx_order_region  (order_region),
    index idx_order_country (order_country)
) engine = InnoDB
  default charset = utf8mb4
  collate = utf8mb4_unicode_ci;


-- ---------------------------------------------------------------------------
-- warehouse.dim_customer  (SCD Type 2)
-- Tracks changes to customer_segment and address over time.
-- A new surrogate key (customer_key) is minted for each version.
-- Only rows with is_current = 1 represent the active customer profile.
--
-- Change detection: row_hash (MD5 of tracked attributes) compared each run.
-- Tracked attributes: customer_segment, customer_city, customer_state,
--                     customer_country, customer_zipcode, customer_street
-- ---------------------------------------------------------------------------
create table if not exists warehouse.dim_customer (
    customer_key        bigint          auto_increment primary key,
    customer_id         int             not null,   -- business / natural key
    customer_fname      varchar(100),
    customer_lname      varchar(100),
    customer_email      varchar(200),
    customer_segment    varchar(100),
    customer_city       varchar(100),
    customer_state      varchar(100),
    customer_country    varchar(100),
    customer_zipcode    varchar(20),
    customer_street     varchar(300),
    -- SCD2 version control columns
    effective_from      date            not null,
    effective_to        date,                       -- NULL = currently active version
    is_current          tinyint(1)      not null    default 1,
    row_hash            varchar(32)     not null,   -- MD5 of tracked attributes

    index idx_customer_id    (customer_id),
    index idx_is_current     (is_current),
    index idx_effective_from (effective_from),
    index idx_segment        (customer_segment)
) engine = InnoDB
  default charset = utf8mb4
  collate = utf8mb4_unicode_ci;


-- ---------------------------------------------------------------------------
-- warehouse.dim_product  (SCD Type 1)
-- Overwrites on change — we care about current product state only.
-- Natural key: product_card_id (unique per product).
-- ---------------------------------------------------------------------------
create table if not exists warehouse.dim_product (
    product_key         int             auto_increment primary key,
    product_card_id     int             not null,
    product_name        varchar(300),
    product_price       decimal(10,2),
    product_status      varchar(20),
    category_id         int,
    category_name       varchar(200),
    department_id       int,
    department_name     varchar(200),
    product_image       varchar(500),
    created_at          timestamp       default current_timestamp,
    updated_at          timestamp       default current_timestamp on update current_timestamp,

    unique key uq_product_card_id (product_card_id),
    index idx_category_id    (category_id),
    index idx_department_id  (department_id)
) engine = InnoDB
  default charset = utf8mb4
  collate = utf8mb4_unicode_ci;


-- ---------------------------------------------------------------------------
-- warehouse.dim_supplier  (SCD Type 2)
-- Supplier = Department in DataCo (natural key = department_id).
-- Tracks changes to performance_tier and composite_score over time — these
-- shift as rolling on-time rates and margin metrics are recalculated each month.
--
-- Tracked attributes: performance_tier, composite_score, on_time_rate
-- ---------------------------------------------------------------------------
create table if not exists warehouse.dim_supplier (
    supplier_key        int             auto_increment primary key,
    supplier_id         int             not null,   -- maps to department_id
    supplier_name       varchar(200)    not null,   -- maps to department_name
    supplier_market     varchar(100),
    on_time_rate        decimal(5,4),
    avg_profit_margin   decimal(8,4),
    composite_score     decimal(5,2),
    performance_tier    varchar(20),   -- 'platinum' | 'gold' | 'silver' | 'bronze'
    -- SCD2 version control columns
    effective_from      date            not null,
    effective_to        date,
    is_current          tinyint(1)      not null    default 1,
    row_hash            varchar(32)     not null,

    index idx_supplier_id       (supplier_id),
    index idx_is_current        (is_current),
    index idx_performance_tier  (performance_tier),
    index idx_effective_from    (effective_from)
) engine = InnoDB
  default charset = utf8mb4
  collate = utf8mb4_unicode_ci;


-- ---------------------------------------------------------------------------
-- warehouse.fct_orders  (grain: one row per order)
-- Partitioned by order year for query performance on time-range scans.
-- FK relationships (documented below — enforced at ETL layer, not DDL):
--   customer_key      → warehouse.dim_customer(customer_key)
--   geography_key     → warehouse.dim_geography(geography_key)
--   order_date_key    → warehouse.dim_date(date_key)
--   shipping_date_key → warehouse.dim_date(date_key)
--   shipping_mode_key → warehouse.dim_shipping_mode(shipping_mode_key)
-- ---------------------------------------------------------------------------
create table if not exists warehouse.fct_orders (
    order_key               bigint          auto_increment,
    order_id                int             not null,
    customer_key            bigint          not null,
    geography_key           int             not null,
    order_date_key          int             not null,   -- FK → dim_date
    shipping_date_key       int,                        -- FK → dim_date (nullable: unshipped)
    shipping_mode_key       tinyint,                    -- FK → dim_shipping_mode
    order_status            varchar(100),
    order_type              varchar(50),
    order_region            varchar(100),
    -- Financial metrics
    sales_amount            decimal(12,2),
    benefit_per_order       decimal(12,2),
    sales_per_customer      decimal(12,2),
    order_profit            decimal(12,2),
    profit_margin_pct       decimal(8,4),
    -- Delivery metrics (pre-computed in staging)
    days_for_shipping_real      tinyint,
    days_for_shipment_scheduled tinyint,
    delivery_delay_days         int,
    is_late_flag                tinyint(1),
    late_delivery_risk          tinyint(1),
    delivery_status             varchar(100),
    -- Lineage
    load_batch_id           varchar(50),
    created_at              timestamp       default current_timestamp,

    primary key (order_key, order_date_key),
    unique key  uq_order_id (order_id, order_date_key),
    index idx_customer_key      (customer_key),
    index idx_order_date_key    (order_date_key),
    index idx_is_late_flag      (is_late_flag),
    index idx_shipping_mode_key (shipping_mode_key)
)
-- Range partition by year so time-range queries scan only relevant partitions.
-- Partition key must be part of the primary key in MySQL.
partition by range (order_date_key) (
    partition p2015 values less than (20160101),
    partition p2016 values less than (20170101),
    partition p2017 values less than (20180101),
    partition p2018 values less than (20190101),
    partition p_future values less than maxvalue
);


-- ---------------------------------------------------------------------------
-- warehouse.fct_order_items  (grain: one row per order line item)
-- FK relationships (ETL-enforced):
--   order_key      → warehouse.fct_orders(order_key)
--   product_key    → warehouse.dim_product(product_key)
--   supplier_key   → warehouse.dim_supplier(supplier_key)
--   order_date_key → warehouse.dim_date(date_key)
-- ---------------------------------------------------------------------------
create table if not exists warehouse.fct_order_items (
    order_item_key          bigint          auto_increment,
    order_item_id           int             not null,
    order_id                int             not null,
    product_key             int             not null,
    supplier_key            int             not null,
    order_date_key          int             not null,
    -- Metrics
    order_item_quantity         int,
    order_item_product_price    decimal(10,2),
    order_item_discount         decimal(10,2),
    order_item_discount_rate    decimal(8,4),
    order_item_total            decimal(12,2),
    order_item_profit_ratio     decimal(8,4),
    order_item_profit           decimal(12,2),
    -- Lineage
    load_batch_id           varchar(50),
    created_at              timestamp       default current_timestamp,

    primary key (order_item_key, order_date_key),
    unique key  uq_order_item_id (order_item_id, order_date_key),
    index idx_order_id      (order_id),
    index idx_product_key   (product_key),
    index idx_supplier_key  (supplier_key),
    index idx_order_date_key (order_date_key)
)
partition by range (order_date_key) (
    partition p2015 values less than (20160101),
    partition p2016 values less than (20170101),
    partition p2017 values less than (20180101),
    partition p2018 values less than (20190101),
    partition p_future values less than maxvalue
);


-- ---------------------------------------------------------------------------
-- warehouse.fct_shipments  (grain: one row per shipment event per order)
-- Tracks delivery outcomes, delay days, and late flags for route analysis.
-- FK relationships (ETL-enforced):
--   shipping_mode_key  → warehouse.dim_shipping_mode(shipping_mode_key)
--   geography_key      → warehouse.dim_geography(geography_key)
--   order_date_key     → warehouse.dim_date(date_key)
--   shipping_date_key  → warehouse.dim_date(date_key)
-- ---------------------------------------------------------------------------
create table if not exists warehouse.fct_shipments (
    shipment_key            bigint          auto_increment,
    order_id                int             not null,
    shipping_mode_key       tinyint,
    shipping_date_key       int,
    order_date_key          int             not null,
    geography_key           int             not null,
    -- Metrics
    shipping_mode               varchar(100),
    delivery_status             varchar(100),
    days_for_shipping_real      tinyint,
    days_for_shipment_scheduled tinyint,
    delivery_delay_days         int,
    is_late_flag                tinyint(1),
    late_delivery_risk          tinyint(1),
    -- Lineage
    load_batch_id           varchar(50),
    created_at              timestamp       default current_timestamp,

    primary key (shipment_key, order_date_key),
    unique key  uq_shipment_order (order_id, order_date_key),
    index idx_shipping_mode_key (shipping_mode_key),
    index idx_shipping_date_key (shipping_date_key),
    index idx_geography_key     (geography_key),
    index idx_is_late_flag      (is_late_flag),
    index idx_delivery_status   (delivery_status)
)
partition by range (order_date_key) (
    partition p2015 values less than (20160101),
    partition p2016 values less than (20170101),
    partition p2017 values less than (20180101),
    partition p2018 values less than (20190101),
    partition p_future values less than maxvalue
);
